-- MySQL Script generated by MySQL Workbench
-- Fri Aug 12 00:56:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tabla_de_perros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tabla_de_perros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tabla_de_perros` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tabla_de_perros` ;

-- -----------------------------------------------------
-- Table `tabla_de_perros`.`dueno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabla_de_perros`.`dueno` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido` VARCHAR(30) NOT NULL,
  `Telefono` VARCHAR(12) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tabla_de_perros`.`perro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabla_de_perros`.`perro` (
  `ID_Perro` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Fecha_nac` DATE NOT NULL,
  `Sexo` VARCHAR(12) NOT NULL,
  `DNI_dueno` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Perro`),
  INDEX `DNI_dueno` (`DNI_dueno` ASC) VISIBLE,
  CONSTRAINT `perro_ibfk_1`
    FOREIGN KEY (`DNI_dueno`)
    REFERENCES `tabla_de_perros`.`dueno` (`DNI`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tabla_de_perros`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tabla_de_perros`.`historial` (
  `ID_Historial` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Perro` INT NULL DEFAULT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `monto` INT NOT NULL,
  PRIMARY KEY (`ID_Historial`),
  INDEX `Perro` (`Perro` ASC) VISIBLE,
  CONSTRAINT `historial_ibfk_1`
    FOREIGN KEY (`Perro`)
    REFERENCES `tabla_de_perros`.`perro` (`ID_Perro`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

#Datos tabla Dueno

INSERT INTO Dueno (DNI, Nombre, Apellido, Telefono, Direccion) VALUES 
 ('29943488', 'Pedro', 'Martinez', '3547445514', 'Milan 25');
 
 INSERT INTO Dueno (DNI, Nombre, Apellido, Telefono, Direccion) VALUES 
 ('29943466', 'Damian', 'Martinez', '3547445866', 'Cordoba 25');
 
 INSERT INTO Dueno (DNI, Nombre, Apellido, Telefono, Direccion) VALUES 
 ('32587458', 'Camila', 'Deniz', '3547445878', 'Chubut 130');
 
 INSERT INTO Dueno (DNI, Nombre, Apellido, Telefono, Direccion) VALUES 
 ('28874586', 'Martina', 'Lopez', '3547445878', 'Chubut 130');
 
 INSERT INTO Dueno (DNI, Nombre, Apellido, Telefono, Direccion) VALUES 
 ('23848648', 'Demian', 'Li', '3547445444', 'Sarmiento 546');
 
 #Datos Tabla Perro
 
INSERT INTO perro (ID_Perro, Nombre, Fecha_nac, Sexo, DNI_dueno) values
("11", "Campeon", "2021/06/05", "M", "29943466");

INSERT INTO perro (ID_Perro, Nombre, Fecha_nac, Sexo, DNI_dueno) values
("10", "Lulu", "2021/06/05", "M", "29943488");

INSERT INTO perro (ID_Perro, Nombre, Fecha_nac, Sexo, DNI_dueno) values
("2", "Miku", "2020/06/05", "F", "32587458");

INSERT INTO perro (ID_Perro, Nombre, Fecha_nac, Sexo, DNI_dueno) values
("3", "CAnela", "2018/05/08", "F", "28874586");

INSERT INTO perro (ID_Perro, Nombre, Fecha_nac, Sexo, DNI_dueno) values
("4", "Luli", "2015/06/10", "F", "23848648");

#Datos Tabla Historial

INSERT INTO historial (ID_Historial, Fecha, Perro, Descripcion, monto) values
("11", "2021/4/2", "10", "Peluqueria", "2000");

INSERT INTO historial (ID_Historial, Fecha, Perro, Descripcion, monto) values
("10", "2022/4/3", "11", "Peluqueria", "2000");

INSERT INTO historial (ID_Historial, Fecha, Perro, Descripcion, monto) values
("4", "2022/10/6", "4", "Control", "3000");

INSERT INTO historial (ID_Historial, Fecha, Perro, Descripcion, monto) values
("2","2018/10/6", "3", "Control", "2000");

INSERT INTO historial (ID_Historial, Fecha, Perro, Descripcion, monto) values
("3", "2020/9/7", "2", "Control", "3000");


# Realice una consulta multitabla que arroje el nombre de todos los perros cuyos dueños se llaman Pedro

SELECT * FROM perro as p, dueno as d WHERE p.DNI_dueno = d.DNI and d.Nombre = "Pedro";